---
title: "Review vietnamcovid19 package"
description: Review vietnamcovid19 package created by Hanh Ngo.
author:
  - name: Zeyu Liu 
    affiliation: Master of Business Analytics, Monash University
    affiliation_url: https://www.monash.edu/study/courses/find-a-course/2021/business-analytics-b6022?gclid=Cj0KCQjwy8f6BRC7ARIsAPIXOjji0OMyDmLQ4OA-UFlChWUF-CGyCVV1ehQgmU7cC4mGLApsgLP7WckaAhW7EALw_wcB&gclsrc=aw.ds
date: 10-30-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Over view of the package

In this blog I will review "vietnamcovid19" package created by Hanh Ngo. This package can be found from [Github](https://github.com/etc5523-2020/r-package-assessment-HanseNgo305) with a [pkgdown website](https://etc5523-2020.github.io/r-package-assessment-HanseNgo305/). The goal of _vietnamcovid19_ is to provide a simple dashboard to report the situation of Covid-19 in Vietnam from the January 2020 to October 2020.

# What I expect

* I expected
1. Successfully download from git hub.
2. Launch_app can find and load shiny application.
3. One function that refactors one part of the user interface side logic of the Shiny app.
4. One function that refactors one part of the server-side logic of the Shiny app.
5. Contains the necessary data to run the Shiny app, and the data can be explored by the user.

This package contain all the necessary component, and can be successfully download from the git hub repository. This package can passes all R CMD check without error or warnings. The pkgdown website worked fine and most of the function well documented. Description file list all the imported package.

# Personal suggestion

## Structure of the package 

ALl the raw data should downloaded in advance and saved in the raw_data folder. The data processing script should also saving in the raw_data folder. Then use usethis::use_data() function to save processed data into data folder. Save data locally in the package also make the package more reproducible.

## %>% function

The usage of pipe operator is kind of misleading. Personally, I think the description with reference to magrittr package is enough.

## Launch_app function

The launch_app() function spent a long time to launch the shiny app. After the in-depth investigation,  I found that the shiny app does not directly use data from the package. It redownloads all necessary data from the server. Using data directly from the data folder would significantly improve the efficiency and reproducibility of this function.

## ref() and output_ref()

Reference should include in the readme file and in the vignette rather than include in a function.

# Ihave learned from reviewing

Through this review of other people’s packages, I learned the importance of documentation. Reasonable and sufficient documentation can help users efficiently understand the functions and usage of the package.

The simplification of function and the pre-processing of data can reduce the time consuming. 



## Appendix

#### Documentation
The package includes all the following forms of documentation:

- [X] **A statement of need** clearly stating problems the software is designed to solve and its target audience in README
- [X] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [X] **Vignette(s)** demonstrating major functionality that runs successfully locally
- [X] **Function Documentation:** for all exported functions in R help
- [X] **Examples** for all exported functions in R Help that run successfully locally
- [ ] **Community guidelines** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

## Functionality
- [x] **Installation:** Installation succeeds as documented.  
- [x] **Functionality:** Any functional claims of the software been confirmed.  
- [x] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.  


